name: Create Production Builds

on:
  push:
    branch: ["develop"]
jobs:
  build_android:
    type: build
    params:
      platform: android
  bash: npx -y expo-doctor
  # build_ios:
  #   type: build 
  #   params:
  #     platform: ios
